services:

  tor:
    image: dperson/torproxy
    container_name: tor
    restart: unless-stopped
    ports:
      - "9050:9050"
      - "9051:9051"
    networks:
      - tor_net

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ./docker/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./docker/pgadmin.env
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - internal_net
      - public_net
    ports:
      - "5050:80"

  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: backend
    env_file:
      - ./docker/backend.env
    depends_on:
      - tor
      - postgres
    networks:
      - tor_net
      - internal_net
      - public_net
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    container_name: frontend
    env_file:
      - ./docker/frontend.env
    depends_on:
      - backend
    networks:
      - public_net
    ports:
      - "${FRONTEND_PORT}:80"

networks:
  tor_net:
    internal: true
  internal_net:
    internal: true
  public_net:

volumes:
  pgdata:
